--DDL
CREATE TABLE INTEGER_TABLE (ID INT NOT NULL PRIMARY KEY, INTEGERS INT);
CREATE TABLE GCD_TABLE (ID INT NOT NULL PRIMARY KEY, GCD INT);
CREATE TABLE GCD_SUM (ID INT NOT NULL PRIMARY KEY, GCD_SUM INT);
CREATE SEQUENCE INT_SEQ_GEN START WITH 500 INCREMENT BY 1;
CREATE SEQUENCE GCD_SEQ_GEN START WITH 500 INCREMENT BY 1;

--DML
insert into GCD_SUM (ID,GCD_SUM) values (1,0);
commit;